AWSTemplateFormatVersion: 2010-09-09

Description: This is our first EC2 Instance we have provisioned using the Cloudformation Template. 

Parameters:
    NameOfMyService:
        Description: This will be the name of my EC2 Instances.
        Type : String
    KeyName:
        Description: Enter the name of the key 
        Type: AWS::EC2::KeyPair::KeyName

		
Resources:
    MyEC2Instance:
        Type: AWS::EC2::Instance
        Properties:
            ImageId: ami-0912f71e06545ad88
            InstanceType: t2.micro
            Tags:
                - Key: Name
                  Value: !Ref NameOfMyService