AWSTemplateFormatVersion: 2010-09-09

Description: This is our first EC2 Instance we have provisioned using the Cloudformation Template. 

Parameters:
    NameOfMyService:
        Description: This will be the name of my EC2 Instances.
        Type : String
    KeyName:
        Description: Enter the name of the key 
        Type: AWS::EC2::KeyPair::KeyName

Mappings:
    MyEc2RegionMap:
        us-east-1:
            AMIId: ami-0ff8a91507f77f867
        us-west-1:
            AMIId: ami-0b59bfac6be064b78
        ap-south-1:
            AMIId: ami-0912f71e06545ad88

Resources:
    MyEC2Instance:
        Type: AWS::EC2::Instance
        Properties:
            ImageId:
                Fn::FindInMap:
                    - MyEc2RegionMap
                    - !Ref AWS::Region
                    - AMIId
            InstanceType: t2.micro
            Tags:
                - Key: Name
                  Value: !Ref NameOfMyService
    
    MySecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Enable port 22 for SSH
            SecurityGroupIngress:
                - IpProtocol: tcp
                  FromPort: 80
                  ToPort: 80
                  CidrIp: 0.0.0.0/0
                - IpProtocol: tcp
                  FromPort: 22
                  ToPort: 22
                  CidrIp: 0.0.0.0/0
    