AWSTemplateFormatVersion: 2010-09-09

Description: Details about my Stack

Parameters:
    NameOfMyService:
        Description: my EC2
        Type: String
    KeyName:
        Description: Enter the key name
        Type: AWS::EC2::KeyPair::KeyName
        

Resources:
    MyEC2Instance:
        Type: AWS::EC2::Instance
        Properties:
            ImageId: ami-0912f71e06545ad88
            InstanceType: t2.micro
            Tags:
                - Key: Name
                  Value: !Ref NameOfMyService
            SecurityGroups:
                - !Ref MySecurityGroup

    
    MySecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: this will enable the SSH 
            SecurityGroupIngress:
                - IpProtocol: tcp 
                  ToPort: 80
                  FromPort: 80
                  CidrIp: 0.0.0.0/0
                - IpProtocol: tcp
                  ToPort: 22
                  FromPort: 22
                  CidrIp: 0.0.0.0/0
